### PR TITLE
Code refctoring and feature support for middleware route handlers

### PR DESCRIPTION
**Pull request by masumsoft**
This PR contains the following changes:

1. Codebase refactoring to get rid of bugs.
2. Controller function parameter passover switch statement is implemented using func.apply instead
3. Support for middleware route handlers that will help to authenticate/authorize/doSomethingElse for a specific controller action using express middleware functions. 
4. Several bug fixes and testcase implementation

### CODE REVIEW

**Comment by masumsoft** [comment]
The code is failing in travis due to old configuration i guess. All are npm errors as only node 0.6 and 0.8 are tested.

**Comment by masumsoft** [comment]
@JulianDuniec Any possibility of accepting this PR?

**Comment by JulianDuniec** [comment]
Sorry about the delay!

**Comment by masumsoft** [comment]
@JulianDuniec Great! I think it would also be nice to have this updates published to npm if you have time.

**Pull request merged**
